# Generated by ClaudeAI
# Server socket
bind = '127.0.0.1:8000'
backlog = 2048

# Worker processes
workers = 1  # Start with 1 for your memory constraints
worker_class = 'geventwebsocket.gunicorn.workers.GeventWebSocketWorker'
threads = 2
worker_connections = 1000
timeout = 30
keepalive = 2

# Process naming
proc_name = 'gunicorn_social50'

# Logging
loglevel = 'info'
accesslog = '-'
errorlog = '-'

# Memory optimization
max_requests = 1000
max_requests_jitter = 50

# SSL
forwarded_allow_ips = '*'
secure_scheme_headers = {
    'X-FORWARDED-PROTOCOL': 'ssl',
    'X-FORWARDED-PROTO': 'https',
    'X-FORWARDED-SSL': 'on'
}