"""added group relation to notification class

Revision ID: 342d86f18580
Revises: 364fecce2927
Create Date: 2024-12-01 00:21:47.814902

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '342d86f18580'
down_revision = '364fecce2927'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.add_column(sa.Column('group_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'group', ['group_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('group_id')

    # ### end Alembic commands ###
