"""notification delete on comment delete

Revision ID: 364fecce2927
Revises: 5df86291a55a
Create Date: 2024-11-30 15:57:14.796593

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '364fecce2927'
down_revision = '5df86291a55a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.drop_constraint('notification_comment_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'comment', ['comment_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('notification_comment_id_fkey', 'comment', ['comment_id'], ['id'])

    # ### end Alembic commands ###
