"""initial migration with postgresql

Revision ID: 452bee1f7cf8
Revises: 
Create Date: 2024-11-19 23:44:53.518278

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '452bee1f7cf8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.add_column(sa.Column('group_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('admins_admin_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'group', ['group_id'], ['id'])
        batch_op.drop_column('admin_id')

    with op.batch_alter_table('members', schema=None) as batch_op:
        batch_op.add_column(sa.Column('group_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('members_member_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'group', ['group_id'], ['id'])
        batch_op.drop_column('member_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('members', schema=None) as batch_op:
        batch_op.add_column(sa.Column('member_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('members_member_id_fkey', 'user', ['member_id'], ['id'])
        batch_op.drop_column('group_id')

    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.add_column(sa.Column('admin_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('admins_admin_id_fkey', 'user', ['admin_id'], ['id'])
        batch_op.drop_column('group_id')

    # ### end Alembic commands ###
