"""post parent delete without ondelete

Revision ID: 708c902fb638
Revises: fae6023527a3
Create Date: 2024-11-30 15:15:30.254871

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '708c902fb638'
down_revision = 'fae6023527a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_constraint('post_parent_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'post', ['parent_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('post_parent_id_fkey', 'post', ['parent_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###
