"""post parent delete set null

Revision ID: fae6023527a3
Revises: 752bc6fbef87
Create Date: 2024-11-30 15:14:52.856668

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fae6023527a3'
down_revision = '752bc6fbef87'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_constraint('post_parent_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'post', ['parent_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('post_parent_id_fkey', 'post', ['parent_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###
